### ISSUE TITLE
建议能否增加测试数据？

### ISSUE THREAD

**Issue by gumanchang** [huanghuidmml/tf1_transformers#1]
您好，能否增加一个可供测试的数据集，这样让后来的同学更加方便的使用，另外README感觉还可以更加详细点。 
Anyway Thanks.

**Comment by huanghuidmml** [comment]
您好，非常感谢你的建议，要素抽取的数据集在这个地址能下载https://github.com/huanghuidmml/cail2019_track2，readme的话，我尽量抽时间出来丰富一下，非常感谢你的支持。
